# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8uQaQhDRtwSbTPOLPUfOENEBWg5wAM6
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('Energy_Efficiency_Smart_Buildings.csv')

# ==========================================================
# 💡 AI Insights for Smart Building Energy Efficiency
# ==========================================================

# 1. How can AI be used to identify inefficiencies in energy consumption in smart buildings?
# ------------------------------------------------------------------
# AI can analyze data from sensors (temperature, lighting, occupancy, etc.) to detect anomalies,
# peak usage times, and inefficient systems (like overused HVAC). It can automatically flag areas
# where energy is being wasted and suggest improvements.

# 2. Build a model to predict the energy consumption of the building based on occupancy and weather data.
# ------------------------------------------------------------------
# You can use regression models (like Linear Regression, Random Forest, or Neural Networks)
# trained on features such as occupancy, outdoor temperature, humidity, and time of day to
# predict energy consumption in real-time or forecast for the future.

# 3. Suggest additional features that could be incorporated into the model to improve its accuracy.
# ------------------------------------------------------------------
# - Building orientation
# - Window-to-wall ratio
# - Insulation quality
# - Appliance usage patterns
# - Real-time electricity pricing
# - Solar panel input (if present)

# 4. What steps can building managers take based on the model's predictions to reduce energy consumption?
# ------------------------------------------------------------------
# - Adjust HVAC settings proactively
# - Schedule cleaning/maintenance of inefficient systems
# - Optimize occupancy planning (use only required spaces)
# - Use automated systems to turn off lights/equipment when not needed

# 5. How can AI-driven solutions contribute to achieving net-zero energy buildings?
# ------------------------------------------------------------------
# - Real-time optimization of energy usage
# - Integration with renewable sources (solar/wind)
# - Predictive control for heating/cooling/lighting
# - Automated energy balancing between storage and grid
# - Data-driven retrofitting suggestions

# ==========================================================
# 📊 1. Correlation Heatmap
# ==========================================================
plt.figure(figsize=(10, 8))
sns.set(style="whitegrid")

# Compute correlation matrix for numeric columns
correlation_matrix = df.corr(numeric_only=True)

# Plot heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", square=True, linewidths=0.5)
plt.title('Correlation Heatmap - Smart Building Features')
plt.tight_layout()
plt.show()

# ==========================================================
# 📈 2. Scatter Plot: Wall Area vs. Heating Load
# ==========================================================
# Check if required columns are in the dataset
if 'Wall Area' in df.columns and 'Heating Load' in df.columns:
    plt.figure(figsize=(8, 6))
    sns.scatterplot(data=df, x='Wall Area', y='Heating Load')
    plt.title('Wall Area vs. Heating Load')
    plt.xlabel('Wall Area')
    plt.ylabel('Heating Load')
    plt.grid(True)
    plt.tight_layout()
    plt.show()